import json
import os
import re

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

CORE_ROLES = [
    'Execution',
    'Planning',
    'MEP',
    'Finishing',
    'Geotechnical',
    'Contracts',
    'Billing',
    'PMO',
    'Safety',
    'QAQC',
    'Design',
    'Rebar Detailing',
    'Quantity Estimation',
    'QA/QC Manager ',
    'Project coordinator',
    'sales',
    'Talent Acquisition/ Recruitment',
    'Quality control',
    'Project or Construction Management',
    'Project Director',
    'Contracts & Procurement',
    'Project Manager',
    'Digital ',
    'Business Development',
    'Project Engineer',
    'Business Development Manager',
    'Finishing Supervisor ',
    'Quantity Estimator',
    'CSA Estimator',
    'AM HR',
    'Finance',
    'Construction Manager',
    'Safety Officer',
    'safety manager',
    'accounts',
    'scaffolding Inspector',
    'Civil Engineer',
    'Quality Engineer',
    'Project Management',
    'plant & Machinery',
    'Deputy safety manager',
    'corporate safety manager',
    'civil supervisor',
    'Manager Planning & Coordination',
    'Senior Architect',
    'Site Engineer',
    'DGM',
    'HR',
    'Project Manager - Infra',
    'Architect',
    'Estimator',
    'Quantity Suveyor ',
]

KEYWORDS = [
    'Software Developer',
    'QAQC',
    'QA',
    'QC',
    'QMS',
    'Quality Control',
    'Quality Audit',
    'Planning',
    'MSP',
    'Primavera',
    'safety',
    'safety manager',
    'ADIS',
    'project coordination',
    'project planning',
    'project manager',
    'PM',
    'project management',
    'Execution',
    'Civil',
    'Finishing',
    'Handover',
    'MEP',
    'MEP Site Engineer',
    'Design',
    'MIDAS',
    'BRIDGE DESIGN',
    'Site Supervisor',
    'Civil Engineer',
    'Civil Site Engineer',
    'Site Execution Engineer',
    'HIRA',
    'HSE',
    'Audit',
    'OH&S ',
    'ISO',
    'HSE plan',
    'QC Engineer',
    'QC Manager',
    'Senior Safety Officer',
    'Senior EHS Officer',
    'sourcing',
    'site visit',
    'closing',
    'lead generation',
    'client coordination',
    'sales',
    'closing sales',
    'real estate',
    'site cordination',
    'site handling',
    'Autocad',
    'Talent Acquisition',
    'Recruitment',
    'NON IT',
    'Warehouse',
    'PEB',
    'Flooring',
    'Civil supervisor',
    'finisher',
    'negotiation',
    'Finishing Engineer',
    'Finishing Site Engineer',
    'Construction management',
    'Project Director',
    'General Manager',
    'Hospitality Projects',
    'Contracts',
    'Procurement',
    'Logistic Project',
    'Estimation & Planning',
    'Safety Head',
    'basline schedule',
    'Brand Strategy',
    'content',
    'Collaboration',
    'Business Development',
    'SEO',
    'ISO – 45001',
    'Corporate safety Manager',
    'Safety Steward',
    "'Safety Supervisor",
    'Safety Officer',
    'Electrical',
    'Mechanical',
    'Plumbing',
    'HVAC',
    'Firefighting',
    'Project Head',
    'interior',
    'fitout',
    'hotel project',
    'villas',
    'project engineer',
    'commercial project',
    'installation ',
    'plotted project',
    'property acquisition',
    'bd',
    'scheduling',
    'tracking',
    'PMO',
    'BTO',
    'Oil& Gas',
    'resorts',
    'inspection',
    'PEB projects',
    'Quantity Estimation',
    'Billing',
    'Earthwork Quantification',
    'Hotel Projects',
    'quality management',
    'checklist',
    'EHS management',
    'Estimator',
    'tower crane',
    'Agtek',
    "CSA Estimation'",
    'Plannng Engineer',
    'Planning Engineer',
    'Civil Site Supervisor',
    'Project Execution Engineer',
    'HR',
    ' Payroll Management',
    ' Employee Relation',
    ' Conducting Trainings',
    'MBA HR',
    'Residential',
    'Plotted development',
    'bridge',
    'metro',
    'elevated corridor',
    'Infra',
    'Elevated metro',
    'Elevated Viaduct',
    'Highway',
    'Bridges',
    'Railway',
    'Finance manager',
    'forecasting',
    'budgeting',
    'MIS',
    'accounting',
    'finance',
    'Construction Manager',
    'Accounts Executive',
    'Scaffolding Inspector',
    'HSE Officer',
    'Accounts',
    'costing',
    'cash flow',
    'project incharge',
    'residential project',
    'Credit Control',
    'Credit Finance',
    'Acounts Receivable',
    'Accounts Receivable',
    'report',
    'barriagator',
    ' REVIT MEP',
    ' Visual lighting',
    'Erection & commissioning',
    'repair',
    'Maintenance',
    'plant & Machinery',
    ' Budgeting',
    ' Claims',
    ' Change management',
    ' Tender Preparation',
    'operations',
    'finishing works',
    ' project planning',
    ' contractor management',
    ' quality assurance',
    'cost control',
    'contract  management',
    ' Pre- tender  estimates',
    ' Pre & Post Contracts',
    ' Quantity survey and Execution',
    'Principal Electrical Engineer - MEP Designs.',
    'Manager Planning',
    'Architect',
    'Civil Engineer  Interior Designer',
    'site execution',
    ' contractor coordination',
    ' quantity surveying and billing',
    ' quality control',
    'site management',
    'DGM',
    'Site Interior Engineer',
    'Interior Site Engineer',
    'Project Manager - Infra',
    'Real Estate - Infra work',
    'Finishing Supervisor',
    'RCC',
    'Mivan',
    'ITP',
    'Documentation',
    'FIDIC',
    'RVNL',
    'Institutional project',
    'Railway Project',
    'Gauge Conversion',
    'Real Estate Projects',
    'Billing Engineer',
    'quantity suveying',
    'Quantity take-off',
    'QS',
    'HRBP',
    'RCC supervisor',
    'BBS',
    'MEP Engineer',
    'RA Bill',
    'Estimation',
    'Interior ',
    'Testing',
    'HT & LT',
    'cost estimation',
    'consultat',
]

INDUSTRIES = [
    (1, 'Accounting/ Finance'),
    (2, 'Agriculture/ Dairy'),
    (3, 'Advertising/ PR/MR/ Event'),
    (4, 'Ceramics/ Sanitary'),
    (5, 'Chemical/ Petrochemical/ Rubber/ Plastic'),
    (6, 'Construction/Engineering/ Cements/ Metals'),
    (7, 'Consumer Durables'),
    (8, 'Electrical/ Switchgears'),
    (9, 'FMCG/Food/ Beverages'),
    (10, 'Glass'),
    (11, 'IT- Software/ Software Services'),
    (12, 'Media/ Dotcom/ Entertainment'),
    (13, 'Oil and Gas/ Power/ Infrastructure/ Energy'),
    (14, 'Pharma/ Biotech/ Clinical search'),
    (15, 'Printing/ Packaging'),
    (16, 'Real estate / Property'),
    (17, 'Recruitment'),
    (18, 'Retail'),
    (19, 'Telecom/ ISP'),
    (20, 'Wellness/ Fitness/ Sports/ Beauty'),
    (21, 'Textiles/ Garment/ Accessories'),
    (22, 'Papler/ Printing/ Packaging'),
    (23, 'Architect/ Interior Design'),
    (24, 'Animation'),
    (25, 'Auto/ Ancillary'),
    (26, 'Aviation/Aerospace firm'),
    (27, 'Banking/ Financial Services / Broking'),
    (28, 'BPO/ ITES'),
    (29, 'Brewery / Distillery'),
    (30, 'Courier/ Transportation/ Freight'),
    (31, 'Education/ Teaching/ Training'),
    (32, 'Export/ Import'),
    (33, 'Facility Management'),
    (34, 'Fertilizers/ Pesticides'),
    (35, 'Food processing'),
    (36, 'Fresh/ Trainee'),
    (37, 'Gems & Jewellary'),
    (38, 'Defence/ Government'),
    (39, 'Heat Ventilation Air Conditioning'),
    (40, 'Hotel/ Restaurants/ Airlines/ Travel'),
    (41, 'Industrial Products/ Heavy Machinery'),
    (42, 'Insurance'),
    (43, 'Internet/ E- Commerce'),
    (44, 'IT Hardworking/ Networking'),
    (45, 'KPO/ Research/ Analytics'),
    (46, 'Legal'),
    (47, 'Medical/ Healthcare/ Hospital'),
    (48, 'Mining'),
    (49, 'NGO/ Social Services'),
    (50, 'Office equipments/ Automation'),
    (51, 'Paper'),
    (52, 'Security/ Law Enforcement'),
    (53, 'Shipping/ Marine'),
    (54, 'Strategy/ Management Consulting Firm'),
    (55, 'Tyres'),
    (56, 'Water Treatment / Waste Management'),
    (57, 'Semiconductors/ Electronics'),
    (58, 'Others'),
]

LOCATIONS = [
    (35, 'Uttar Pradesh', 'States'),
    (24, 'Manipur', 'States'),
    (25, 'Meghalaya', 'States'),
    (26, 'Mizoram', 'States'),
    (27, 'Nagaland', 'States'),
    (28, 'Odisha / Orissa', 'States'),
    (30, 'Rajasthan', 'States'),
    (31, 'Sikkim', 'States'),
    (32, 'Telangana', 'States'),
    (33, 'Tripura', 'States'),
    (34, 'Union Territories', 'States'),
    (29, 'Punjab', 'States'),
    (36, 'Uttaranchal', 'States'),
    (37, 'West Bengal', 'States'),
    (22, 'Kerala', 'States'),
    (9, 'Maharashtra', 'States'),
    (10, 'Goa', 'States'),
    (11, 'Andhra Pradesh', 'States'),
    (12, 'Assam', 'States'),
    (13, 'Arunachal Pradesh', 'States'),
    (14, 'Bihar', 'States'),
    (15, 'Chhattisgarh', 'States'),
    (17, 'Haryana', 'States'),
    (23, 'Madhya Pradesh', 'States'),
    (18, 'Himachal Pradesh', 'States'),
    (19, 'Jammu & Kashmir', 'States'),
    (20, 'Karnataka', 'States'),
    (21, 'Tamilnadu', 'States'),
    (16, 'Gujarat', 'States'),
    (48, 'Aurangabad', 'Top Metropolitan Cities'),
    (49, 'Rajkot', 'Top Metropolitan Cities'),
    (50, 'Shimla', 'Top Metropolitan Cities'),
    (51, 'Chandigarh', 'Top Metropolitan Cities'),
    (7, 'Kolkata', 'Top Metropolitan Cities'),
    (6, 'Pune', 'Top Metropolitan Cities'),
    (5, 'Chennai', 'Top Metropolitan Cities'),
    (4, 'Bangalore / Bengaluru', 'Top Metropolitan Cities'),
    (3, 'Delhi / NCR', 'Top Metropolitan Cities'),
    (2, 'Ahmedabad', 'Top Metropolitan Cities'),
    (47, 'Patna', 'Top Metropolitan Cities'),
    (46, 'Bhopal', 'Top Metropolitan Cities'),
    (45, 'Indore', 'Top Metropolitan Cities'),
    (44, 'Nagpur', 'Top Metropolitan Cities'),
    (43, 'Kanpur', 'Top Metropolitan Cities'),
    (42, 'Lucknow', 'Top Metropolitan Cities'),
    (41, 'Madgaon', 'Top Metropolitan Cities'),
    (40, 'Ponda', 'Top Metropolitan Cities'),
    (8, 'Hyderabad / Secunderabad', 'Top Metropolitan Cities'),
    (1, 'Mumbai', 'Top Metropolitan Cities'),
    (56, 'Middle East', 'Other'),
    (55, 'Dubai', 'Other'),
    (54, 'UAE', 'Other'),
    (53, 'US', 'Other'),
    (52, 'kenya', 'Other'),
    (39, 'Other', 'Other'),
    (38, 'International Location / Overseas', 'Other'),
]

FA_RECORDS = [
    ('Accounting/Tax/Company Secretary/Audit', 'Accounts', 'Cost Accountant', 2),
    ('Accounting/Tax/Company Secretary/Audit', 'Accounts', 'Taxation (Direct/ Indirect) Manager', 3),
    ('Accounting/Tax/Company Secretary/Audit', 'Accounts', 'Accounts Manager', 4),
    ('Accounting/Tax/Company Secretary/Audit', 'Accounts', 'Financial Accountant', 5),
    ('Accounting/Tax/Company Secretary/Audit', 'Accounts', 'ICWA', 6),
    ('Accounting/Tax/Company Secretary/Audit', 'Accounts', 'Chartered Accountant', 7),
    ('Accounting/Tax/Company Secretary/Audit', 'Accounts', 'Accounts Executive/ Accountant', 1),
    ('Graphic/ Web Designer', 'General', 'UI/UX Developer', 8),
    ('Graphic/ Web Designer', 'General', 'Web Designer', 9),
    ('Graphic/ Web Designer', 'General', 'Graphic Designer', 10),
    ('Graphic/ Web Designer', 'General', 'Design Developer', 11),
    ('HR/ Admin/PM/IR', 'Administration/ Facility Management', 'Manager/ Sr. Manager - Facility Management', 19),
    ('HR/ Admin/PM/IR', 'Administration/ Facility Management', 'Executive/Sr. Executive- Facility Management', 18),
    ('HR/ Admin/PM/IR', 'Administration/ Facility Management', 'Manager/ Sr. Manager - Administration', 17),
    ('HR/ Admin/PM/IR', 'Administration/ Facility Management', 'Executive/Sr. Executive- Administration', 16),
    ('HR/ Admin/PM/IR', 'HR/Recruitment/IR', 'HR Executive/ Manager', 12),
    ('HR/ Admin/PM/IR', 'HR/Recruitment/IR', 'Employee Relations Executive/ Manager', 15),
    ('HR/ Admin/PM/IR', 'HR/Recruitment/IR', 'Payroll Executive', 14),
    ('HR/ Admin/PM/IR', 'HR/Recruitment/IR', 'Recruitment Executive/ Manager', 13),
    ('HR/ Admin/PM/IR', 'Senior Management', 'Head/ VP/GM- Admin & Facilities', 22),
    ('HR/ Admin/PM/IR', 'Senior Management', 'Head/ VP/GM- Facility Management', 24),
    ('HR/ Admin/PM/IR', 'Senior Management', 'Head/ VP/GM- Compensation & Benefits', 23),
    ('HR/ Admin/PM/IR', 'Senior Management', 'Head/ VP/GM- Recruitment', 21),
    ('HR/ Admin/PM/IR', 'Senior Management', 'Head/ VP/GM- HR', 20),
    ('Mkg./Advg./ MR/ Media Planning/ PR/ Corp. Comm.', 'General', 'Marketing Executive/ Manager', 33),
    ('Mkg./Advg./ MR/ Media Planning/ PR/ Corp. Comm.', 'General', 'Social Media Marketing Manager', 38),
    ('Mkg./Advg./ MR/ Media Planning/ PR/ Corp. Comm.', 'General', 'SEO Specilist/ Analyst/ Lead', 37),
    ('Mkg./Advg./ MR/ Media Planning/ PR/ Corp. Comm.', 'General', 'International Marketing Manager', 36),
    ('Mkg./Advg./ MR/ Media Planning/ PR/ Corp. Comm.', 'General', 'Regional Marketing Manager', 35),
    ('Mkg./Advg./ MR/ Media Planning/ PR/ Corp. Comm.', 'General', 'Branch Marketing Manager', 34),
    ('Mkg./Advg./ MR/ Media Planning/ PR/ Corp. Comm.', 'General', 'Corporate/ Brand Executive/ Manager', 32),
    ('Mkg./Advg./ MR/ Media Planning/ PR/ Corp. Comm.', 'General', 'Corp. Communication Executive/ Manager', 31),
    ('Mkg./Advg./ MR/ Media Planning/ PR/ Corp. Comm.', 'General', 'Media Planning Executive/ Manager', 30),
    ('Mkg./Advg./ MR/ Media Planning/ PR/ Corp. Comm.', 'General', 'Key Account Executive/ Manager', 29),
    ('Mkg./Advg./ MR/ Media Planning/ PR/ Corp. Comm.', 'General', 'Client Serving Executive/ Manager', 28),
    ('Packaging Development', 'General', 'Packaging Development Executive/ Manager', 39),
    ('Packaging Development', 'General', 'Head/ VP/GM- Packaging Development', 40),
    ('Production/ Service Engineering/ Manufacturing/ Maintenance', 'Safety/ Health / Environment', 'Safety Officer / Executive/ Manager', 49),
    ('Production/ Service Engineering/ Manufacturing/ Maintenance', 'Safety/ Health / Environment', 'Health  Officer/ Executive/ Manager', 50),
    ('Production/ Service Engineering/ Manufacturing/ Maintenance', 'Safety/ Health / Environment', 'Environment Officer/ Executive/ Manager', 51),
    ('Production/ Service Engineering/ Manufacturing/ Maintenance', 'Senior Management', 'Head/VP/GM  Production/ Manufacturing / Maintenance', 52),
    ('Production/ Service Engineering/ Manufacturing/ Maintenance', 'Senior Management', 'Head/VP/GM - Safety/ Health/ Environment', 54),
    ('Production/ Service Engineering/ Manufacturing/ Maintenance', 'Senior Management', 'Head/VP/GM - QA QC', 53),
    ('Production/ Service Engineering/ Manufacturing/ Maintenance', 'Production/ Manufacturing/ Maintenance', 'Factory Head', 42),
    ('Production/ Service Engineering/ Manufacturing/ Maintenance', 'Production/ Manufacturing/ Maintenance', 'Product Development Executive/Manager', 46),
    ('Production/ Service Engineering/ Manufacturing/ Maintenance', 'Production/ Manufacturing/ Maintenance', 'Service/ Maintenance- Executive/ Manager', 47),
    ('Production/ Service Engineering/ Manufacturing/ Maintenance', 'Production/ Manufacturing/ Maintenance', 'QA-QC Executive/ Manager', 45),
    ('Production/ Service Engineering/ Manufacturing/ Maintenance', 'Production/ Manufacturing/ Maintenance', 'Project Manager- Production/ Manufacturing / Maintenance', 48),
    ('Production/ Service Engineering/ Manufacturing/ Maintenance', 'Production/ Manufacturing/ Maintenance', 'Production Executive/ Manager', 44),
    ('Production/ Service Engineering/ Manufacturing/ Maintenance', 'Production/ Manufacturing/ Maintenance', 'Industrial Engineer', 41),
    ('Production/ Service Engineering/ Manufacturing/ Maintenance', 'Production/ Manufacturing/ Maintenance', 'Design Engineer/ Manager', 43),
    ('Project Management/ Site Engineers', 'Project Management', 'Project Manager - Telecom', 55),
    ('Project Management/ Site Engineers', 'Project Management', 'Project Manager - IT/ Software', 56),
    ('Project Management/ Site Engineers', 'Project Management', 'Project Manager- Production/ Manufacturing / Maintenance', 57),
    ('Project Management/ Site Engineers', 'Site Engineers', 'Mechanical Engineer-others', 63),
    ('Project Management/ Site Engineers', 'Site Engineers', 'Structrual Engineer- Building/ Bridge', 64),
    ('Project Management/ Site Engineers', 'Site Engineers', 'Structrual Engineer- others', 65),
    ('Project Management/ Site Engineers', 'Site Engineers', 'Construction- General Building/ Heavy/ Residential', 66),
    ('Project Management/ Site Engineers', 'Site Engineers', 'Mechanical Engineer- Plumbing / Fire Protection/ HVAC', 62),
    ('Project Management/ Site Engineers', 'Site Engineers', 'Mechanical Engineer- Telecom/ Industrial/ Commercial', 61),
    ('Project Management/ Site Engineers', 'Site Engineers', 'Civil Engineer- others', 59),
    ('Project Management/ Site Engineers', 'Site Engineers', 'Civil Engineer- Telecom/ Highway Roadway', 58),
    ('Project Management/ Site Engineers', 'Site Engineers', 'Electrical Engineer- Telecom/ Industrial/ Commercial', 60),
    ('Purchase/SCM', 'General', 'Purchase Executive/ Manager', 25),
    ('Purchase/SCM', 'General', 'Material Management Executive/ Manager', 26),
    ('Purchase/SCM', 'General', 'Logistics Executive/ Manager', 27),
    ('R & D/ Engineering Design', 'General', 'R & D Executive/ Manager', 67),
    ('R & D/ Engineering Design', 'General', 'Design/ Sr. Design Engineer', 68),
    ('R & D/ Engineering Design', 'General', 'Project Lead', 69),
    ('Sales/ Business Development/ Client Servicing', 'Retail/ Corporate/ Institutional /Channel Sales', 'Client Servicing / Key Account Manager', 72),
    ('Sales/ Business Development/ Client Servicing', 'Retail/ Corporate/ Institutional /Channel Sales', 'Client Relationship Manager', 76),
    ('Sales/ Business Development/ Client Servicing', 'Retail/ Corporate/ Institutional /Channel Sales', 'Territory Executive / Manager', 75),
    ('Sales/ Business Development/ Client Servicing', 'Retail/ Corporate/ Institutional /Channel Sales', 'Regional Executive/ Manager', 74),
    ('Sales/ Business Development/ Client Servicing', 'Retail/ Corporate/ Institutional /Channel Sales', 'Area Sales Executive/ Manager', 73),
    ('Sales/ Business Development/ Client Servicing', 'Retail/ Corporate/ Institutional /Channel Sales', 'BD/ Branch / Regional Manager', 71),
    ('Sales/ Business Development/ Client Servicing', 'Retail/ Corporate/ Institutional /Channel Sales', 'Sales Officer/ Executive/ Manager', 70),
    ('Sales/ Business Development/ Client Servicing', 'Senior Management', 'Head/ VP/GM- Sales/ BD', 77),
    ('Software Development- Application Programming', 'General', 'Software Development', 78),
    ('Software Development- Application Programming', 'General', 'Team Lead /Tech Lead', 79),
    ('Software Development- Application Programming', 'General', 'Project Lead', 80),
    ('Software Development- Application Programming', 'General', 'Testing engineer', 81),
    ('Software Development- Application Programming', 'General', 'Product Manager', 82),
]

EDU_RECORDS = [
    ('Diploma', 'Electrical', 'Electrical', 119),
    ('Diploma', 'Fire & Safety', 'Fire & Safety', 121),
    ('Diploma', 'Mechanical', 'Mechanical', 120),
    ('Diploma', 'Civil', 'Civil', 116),
    ('Graduation Qualification', 'Bachor of Arcitect (B. Arch.)', 'Architect', 25),
    ('Graduation Qualification', 'Bachor of Arcitect (B. Arch.)', 'Others', 26),
    ('Graduation Qualification', 'Diploma', 'Computers', 54),
    ('Graduation Qualification', 'Diploma', 'Insurance', 60),
    ('Graduation Qualification', 'Diploma', 'Tourism', 59),
    ('Graduation Qualification', 'Diploma', 'Import/ Export', 58),
    ('Graduation Qualification', 'Diploma', 'Management', 57),
    ('Graduation Qualification', 'Diploma', 'Architect', 56),
    ('Graduation Qualification', 'Diploma', 'Graphic / Web Designing', 55),
    ('Graduation Qualification', 'Diploma', 'Chemical', 53),
    ('Graduation Qualification', 'Diploma', 'Engineering', 52),
    ('Graduation Qualification', 'Diploma', 'Mechanical', 51),
    ('Graduation Qualification', 'Diploma', 'Electrical', 50),
    ('Graduation Qualification', 'Diploma', 'Civil', 49),
    ('Graduation Qualification', 'BE / B.Tech (From Top Ranked Colleges)', 'Energy', 47),
    ('Graduation Qualification', 'BE / B.Tech (From Top Ranked Colleges)', 'Others', 48),
    ('Graduation Qualification', 'BE / B.Tech (From Top Ranked Colleges)', 'Agriculture', 46),
    ('Graduation Qualification', 'BE / B.Tech (From Top Ranked Colleges)', 'Production/ Industrial', 45),
    ('Graduation Qualification', 'BE / B.Tech (From Top Ranked Colleges)', 'Telecom', 44),
    ('Graduation Qualification', 'BE / B.Tech (From Top Ranked Colleges)', 'Computers', 43),
    ('Graduation Qualification', 'BE / B.Tech (From Top Ranked Colleges)', 'Mechanical', 42),
    ('Graduation Qualification', 'BE / B.Tech (From Top Ranked Colleges)', 'Electrical', 41),
    ('Graduation Qualification', 'BE / B.Tech (From Top Ranked Colleges)', 'Civil', 40),
    ('Graduation Qualification', 'BE / B.Tech', 'Production/ Industrial', 36),
    ('Graduation Qualification', 'BE / B.Tech', 'Others', 39),
    ('Graduation Qualification', 'BE / B.Tech', 'Energy', 38),
    ('Graduation Qualification', 'BE / B.Tech', 'Agriculture', 37),
    ('Graduation Qualification', 'BE / B.Tech', 'Telecom', 35),
    ('Graduation Qualification', 'BE / B.Tech', 'Computers', 34),
    ('Graduation Qualification', 'BE / B.Tech', 'Mechanical', 33),
    ('Graduation Qualification', 'BE / B.Tech', 'Electrical', 32),
    ('Graduation Qualification', 'BE / B.Tech', 'Civil', 31),
    ('Graduation Qualification', 'Bachelor of Science (B.Sc)', 'Chemistry', 9),
    ('Graduation Qualification', 'Bachelor of Science (B.Sc)', 'Physics', 10),
    ('Graduation Qualification', 'Bachelor of Science (B.Sc)', 'Biology', 11),
    ('Graduation Qualification', 'Bachelor of Science (B.Sc)', 'Environmental Science', 13),
    ('Graduation Qualification', 'Bachelor of Science (B.Sc)', 'Maths', 12),
    ('Graduation Qualification', 'Bachelor of Science (B.Sc)', 'Food Technology', 18),
    ('Graduation Qualification', 'Bachelor of Science (B.Sc)', 'Dairy Technology', 17),
    ('Graduation Qualification', 'Bachelor of Science (B.Sc)', 'Agriculture', 16),
    ('Graduation Qualification', 'Bachelor of Science (B.Sc)', 'Computers ', 15),
    ('Graduation Qualification', 'Bachelor of Science (B.Sc)', 'Electronics', 14),
    ('Graduation Qualification', 'Bachelor of Pharmacy (B. Pharma)', 'Pharmacy', 23),
    ('Graduation Qualification', 'Bachelor of Pharmacy (B. Pharma)', 'Others', 24),
    ('Graduation Qualification', 'Bachelor of Education (B. Ed.)', 'Others', 28),
    ('Graduation Qualification', 'Bachelor of Education (B. Ed.)', 'Education', 27),
    ('Graduation Qualification', 'Bachelor of Computer Application (BCA)', 'Others', 30),
    ('Graduation Qualification', 'Bachelor of Computer Application (BCA)', 'Computers', 29),
    ('Graduation Qualification', 'Bachelor of Commerce (B.Com)', 'Commerce', 7),
    ('Graduation Qualification', 'Bachelor of Commerce (B.Com)', 'Others', 8),
    ('Graduation Qualification', 'Bachelor of Business Management (BMS)', 'Management', 21),
    ('Graduation Qualification', 'Bachelor of Business Management (BMS)', 'Others', 22),
    ('Graduation Qualification', 'Bachelor of Business Administration (BBA)', 'Management', 19),
    ('Graduation Qualification', 'Bachelor of Business Administration (BBA)', 'Others', 20),
    ('Graduation Qualification', 'Bachelor of Arts (BA)', 'Communication', 2),
    ('Graduation Qualification', 'Bachelor of Arts (BA)', 'English', 3),
    ('Graduation Qualification', 'Bachelor of Arts (BA)', 'Economics', 4),
    ('Graduation Qualification', 'Bachelor of Arts (BA)', 'Maths', 5),
    ('Graduation Qualification', 'Bachelor of Arts (BA)', 'PR/ Advertising', 6),
    ('Graduation Qualification', 'Bachelor of Arts (BA)', 'Art & Humanities', 1),
    ('Post Graduation Qualification', 'Company Secretary (CS)', 'Company Secretary (CS)', 112),
    ('Post Graduation Qualification', 'NICMAR', 'Prroject Management', 117),
    ('Post Graduation Qualification', 'Masters of Technology (M. Tech)', 'Telecom', 98),
    ('Post Graduation Qualification', 'Masters of Technology (M. Tech)', 'Others', 101),
    ('Post Graduation Qualification', 'Masters of Technology (M. Tech)', 'Agriculture', 100),
    ('Post Graduation Qualification', 'Masters of Technology (M. Tech)', 'Energy', 99),
    ('Post Graduation Qualification', 'Masters of Technology (M. Tech)', 'Production/ Industrial', 97),
    ('Post Graduation Qualification', 'Masters of Technology (M. Tech)', 'Computers', 96),
    ('Post Graduation Qualification', 'Masters of Technology (M. Tech)', 'Electrical', 95),
    ('Post Graduation Qualification', 'Masters of Technology (M. Tech)', 'Civil', 94),
    ('Post Graduation Qualification', 'Masters of Technology (M. Tech)', 'Mechanical', 93),
    ('Post Graduation Qualification', 'Masters of Science (M.Sc)', 'Dairy Technology', 77),
    ('Post Graduation Qualification', 'Masters of Science (M.Sc)', 'Environmental Science', 73),
    ('Post Graduation Qualification', 'Masters of Science (M.Sc)', 'Chemistry', 69),
    ('Post Graduation Qualification', 'Masters of Science (M.Sc)', 'Physics', 70),
    ('Post Graduation Qualification', 'Masters of Science (M.Sc)', 'Biology', 71),
    ('Post Graduation Qualification', 'Masters of Science (M.Sc)', 'Electronics', 74),
    ('Post Graduation Qualification', 'Masters of Science (M.Sc)', 'Maths', 72),
    ('Post Graduation Qualification', 'Masters of Science (M.Sc)', 'Computers', 75),
    ('Post Graduation Qualification', 'Masters of Science (M.Sc)', 'Agriculture', 76),
    ('Post Graduation Qualification', 'Masters of Science (M.Sc)', 'Food Technology', 78),
    ('Post Graduation Qualification', 'Masters of Pharmacy (M. Pharma)', 'Pharmacy', 102),
    ('Post Graduation Qualification', 'Masters of Pharmacy (M. Pharma)', 'Others', 103),
    ('Post Graduation Qualification', 'Masters of Law (M M L)', 'Others', 115),
    ('Post Graduation Qualification', 'Masters of Law (M M L)', 'Law', 114),
    ('Post Graduation Qualification', 'Masters of Education (M. Ed.)', 'Others', 107),
    ('Post Graduation Qualification', 'Masters of Education (M. Ed.)', 'Education', 106),
    ('Post Graduation Qualification', 'Masters of Computer Application (MCA)', 'Others', 109),
    ('Post Graduation Qualification', 'Masters of Computer Application (MCA)', 'Computers', 108),
    ('Post Graduation Qualification', 'Masters of Commerce (M.Com)', 'Commerce', 67),
    ('Post Graduation Qualification', 'Masters of Commerce (M.Com)', 'Others', 68),
    ('Post Graduation Qualification', 'Masters of Business Management (MMS / PGDM)', 'Advertising/ Mass Communication', 86),
    ('Post Graduation Qualification', 'Masters of Business Management (MMS / PGDM)', 'Finance', 87),
    ('Post Graduation Qualification', 'Masters of Business Management (MMS / PGDM)', 'Operations', 88),
    ('Post Graduation Qualification', 'Masters of Business Management (MMS / PGDM)', 'Marketing', 89),
    ('Post Graduation Qualification', 'Masters of Business Management (MMS / PGDM)', 'Information Technology', 90),
    ('Post Graduation Qualification', 'Masters of Business Management (MMS / PGDM)', 'HR/ Industrial Relation', 91),
    ('Post Graduation Qualification', 'Masters of Business Management (MMS / PGDM)', 'International Business', 92),
    ('Post Graduation Qualification', 'Masters of Business Administration (MBA / PGDM)', 'Information Technology', 83),
    ('Post Graduation Qualification', 'Masters of Business Administration (MBA / PGDM)', 'International Business', 85),
    ('Post Graduation Qualification', 'Masters of Business Administration (MBA / PGDM)', 'HR/ Industrial Relation', 84),
    ('Post Graduation Qualification', 'Masters of Business Administration (MBA / PGDM)', 'Marketing', 82),
    ('Post Graduation Qualification', 'Masters of Business Administration (MBA / PGDM)', 'Operations', 81),
    ('Post Graduation Qualification', 'Masters of Business Administration (MBA / PGDM)', 'Finance', 80),
    ('Post Graduation Qualification', 'Masters of Business Administration (MBA / PGDM)', 'Advertising/ Mass Communication', 79),
    ('Post Graduation Qualification', 'Masters of Business Administration (MBA / PGDM)', 'Construction Management', 118),
    ('Post Graduation Qualification', 'Masters of Arts (MA)', 'English', 63),
    ('Post Graduation Qualification', 'Masters of Arts (MA)', 'Art & Humanities', 61),
    ('Post Graduation Qualification', 'Masters of Arts (MA)', 'PR/ Advertising', 66),
    ('Post Graduation Qualification', 'Masters of Arts (MA)', 'Maths', 65),
    ('Post Graduation Qualification', 'Masters of Arts (MA)', 'Economics', 64),
    ('Post Graduation Qualification', 'Masters of Arts (MA)', 'Communication', 62),
    ('Post Graduation Qualification', 'Masters  of Arcitect (M. Arch.)', 'Architect', 104),
    ('Post Graduation Qualification', 'Masters  of Arcitect (M. Arch.)', 'Others', 105),
    ('Post Graduation Qualification', 'Journalism/ Mass Communication', 'Journalism/ Mass Communication', 111),
    ('Post Graduation Qualification', 'ICWA', 'ICWA', 113),
    ('Post Graduation Qualification', 'Chartered Accountant (CA)', 'Chartered Accountant (CA)', 110),
    ('Under Graduate', 'HSC', 'HSC', 123),
    ('Under Graduate', 'ITI', 'ITI', 124),
    ('Under Graduate', 'SSC', 'SSC', 122),
]


def main():
    # 1. Assemble original v6 dataset
    v6_data = {
        "_meta": {
            "source": "Skill Groomers production master endpoints supplied by user",
            "version": 6,
            "notes": "Exact website spellings preserved. Matching normalizes internally only."
        },
        "core_roles": CORE_ROLES,
        "keywords": KEYWORDS,
        "industries": [{"id": i, "name": n, "active": 1} for i, n in INDUSTRIES],
        "locations": [{"id": i, "name": n, "category": c, "active": 1} for i, n, c in LOCATIONS],
        "functional_area_records": [
            {"functional_area": f, "sub_functional_area": s, "role": r, "role_id": rid}
            for f, s, r, rid in FA_RECORDS
        ],
        "education_records": [
            {"qualification": q, "course": c, "specialization": s, "education_id": eid, "active": 1}
            for q, c, s, eid in EDU_RECORDS
        ]
    }

    v6_path = os.path.join(BASE_DIR, "skillgroomers_master_data_v6.json")
    with open(v6_path, "w", encoding="utf-8") as f:
        json.dump(v6_data, f, indent=2, ensure_ascii=False)
    print(f"✓ Successfully wrote: {v6_path}")

    # 2. Assemble sanitized v7 dataset
    def clean_val(s):
        if not isinstance(s, str):
            return s
        return re.sub(r"\s+", " ", s.strip().strip("'\"").strip())

    cleaned_core = []
    seen_core = set()
    for r in CORE_ROLES:
        c = clean_val(r)
        if c and c.lower() not in seen_core:
            seen_core.add(c.lower())
            cleaned_core.append(c)

    cleaned_kw = []
    seen_kw = set()
    for k in KEYWORDS:
        c = clean_val(k)
        if c and c.lower() not in seen_kw:
            seen_kw.add(c.lower())
            cleaned_kw.append(c)

    v7_data = {
        "_meta": {
            "source": "Skill Groomers production master endpoints supplied by user",
            "version": 7,
            "notes": "Sanitized: trimmed whitespace, removed stray quotes, deduplicated keywords."
        },
        "core_roles": cleaned_core,
        "keywords": cleaned_kw,
        "industries": [{"id": i, "name": clean_val(n), "active": 1} for i, n in INDUSTRIES],
        "locations": [{"id": i, "name": clean_val(n), "category": clean_val(c), "active": 1} for i, n, c in LOCATIONS],
        "functional_area_records": [
            {"functional_area": clean_val(f), "sub_functional_area": clean_val(s), "role": clean_val(r), "role_id": rid}
            for f, s, r, rid in FA_RECORDS
        ],
        "education_records": [
            {"qualification": clean_val(q), "course": clean_val(c), "specialization": clean_val(s), "education_id": eid, "active": 1}
            for q, c, s, eid in EDU_RECORDS
        ]
    }

    v7_path = os.path.join(BASE_DIR, "skillgroomers_master_data_v7.json")
    with open(v7_path, "w", encoding="utf-8") as f:
        json.dump(v7_data, f, indent=2, ensure_ascii=False)
    print(f"✓ Successfully wrote: {v7_path}")
    print("\nMaster data files are ready for CV Analyzer!")


if __name__ == "__main__":
    main()